//------------------------------------------------------------------------------ 
// <copyright file="DataColumnSelectionConverter.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

namespace System.Web.UI.Design { 
 
    using System;
    using System.Collections; 
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Data;
    using System.Design; 
    using System.Diagnostics;
    using System.Runtime.InteropServices; 
    using System.Globalization; 
    using System.Web.UI.Design.WebControls;
    using System.Web.UI.WebControls; 

    /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter"]/*' />
    /// <devdoc>
    ///    <para> 
    ///       Provides design-time support for a gridview's bound field's data field properties.
    ///    </para> 
    /// </devdoc> 
    [System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.Demand, Flags=System.Security.Permissions.SecurityPermissionFlag.UnmanagedCode)]
    public class DataColumnSelectionConverter : TypeConverter { 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.DataColumnSelectionConverter"]/*' />
        /// <devdoc>
        ///    <para> 
        ///       Initializes a new instance of <see cref='System.Web.UI.Design.DataColumnSelectionConverter'/>.
        ///    </para> 
        /// </devdoc> 
        public DataColumnSelectionConverter() {
        } 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.CanConvertFrom"]/*' />
        /// <devdoc>
        ///    <para> 
        ///       Gets a value indicating whether this converter can
        ///       convert an object in the given source type to the native type of the converter 
        ///       using the context. 
        ///    </para>
        /// </devdoc> 
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) {
            if (sourceType == typeof(string)) {
                return true;
            } 
            return false;
        } 
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.ConvertFrom"]/*' />
        /// <devdoc> 
        ///    <para>
        ///       Converts the given object to the converter's native type.
        ///    </para>
        /// </devdoc> 
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) {
            if (value == null) { 
                return String.Empty; 
            }
            else if (value.GetType() == typeof(string)) { 
                return (string)value;
            }
            throw GetConvertFromException(value);
        } 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValues"]/*' /> 
        /// <devdoc> 
        ///    <para>
        ///       Gets the data fields of the bound fields and autogenerated fields in the current gridview for the 
        ////      RowHeaderColumn and SummaryHeaderColumn properties.
        ///    </para>
        /// </devdoc>
        public override StandardValuesCollection GetStandardValues(ITypeDescriptorContext context) { 
            string[] names = null;
            ArrayList namesList = new ArrayList(); 
 
            if (context != null) {
                IComponent component = context.Instance as IComponent; 
                if (component != null) {
                    GridView gridView = component as GridView;
                    if (gridView != null) {
                        if (gridView.AutoGenerateColumns) { 
                            // add all the fields
                            DataFieldConverter dataFieldConverter = new DataFieldConverter(); 
                            StandardValuesCollection values = dataFieldConverter.GetStandardValues(context); 
                            foreach (object value in values) {
                                namesList.Add(value); 
                            }
                        }
                        DataControlFieldCollection fields = gridView.Columns;
                        foreach (DataControlField field in fields) { 
                            BoundField boundField = field as BoundField;
                            if (boundField != null) { 
                                string dataField = boundField.DataField; 
                                if (!namesList.Contains(dataField)) {
                                    namesList.Add(dataField); 
                                }
                            }
                        }
 
                        namesList.Sort();
                        names = new string[namesList.Count]; 
                        namesList.CopyTo(names, 0); 
                    }
                } 
            }
            return new StandardValuesCollection(names);
        }
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValuesExclusive"]/*' />
        /// <devdoc> 
        ///    <para> 
        ///       Gets a value indicating whether the collection of standard values returned from
        ///    <see cref='System.ComponentModel.TypeConverter.GetStandardValues'/> is an exclusive 
        ///       list of possible values, using the specified context.
        ///    </para>
        /// </devdoc>
        public override bool GetStandardValuesExclusive(ITypeDescriptorContext context) { 
            return false;
        } 
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValuesSupported"]/*' />
        /// <devdoc> 
        ///    <para>
        ///       Gets a value indicating whether this object supports a standard set of values
        ///       that can be picked from a list.
        ///    </para> 
        /// </devdoc>
        public override bool GetStandardValuesSupported(ITypeDescriptorContext context) { 
            if (context != null && context.Instance is IComponent) { 
                // We only support the dropdown in single-select mode.
                return true; 
            }
            return false;
        }
    } 
}

// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
//------------------------------------------------------------------------------ 
// <copyright file="DataColumnSelectionConverter.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

namespace System.Web.UI.Design { 
 
    using System;
    using System.Collections; 
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Data;
    using System.Design; 
    using System.Diagnostics;
    using System.Runtime.InteropServices; 
    using System.Globalization; 
    using System.Web.UI.Design.WebControls;
    using System.Web.UI.WebControls; 

    /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter"]/*' />
    /// <devdoc>
    ///    <para> 
    ///       Provides design-time support for a gridview's bound field's data field properties.
    ///    </para> 
    /// </devdoc> 
    [System.Security.Permissions.SecurityPermission(System.Security.Permissions.SecurityAction.Demand, Flags=System.Security.Permissions.SecurityPermissionFlag.UnmanagedCode)]
    public class DataColumnSelectionConverter : TypeConverter { 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.DataColumnSelectionConverter"]/*' />
        /// <devdoc>
        ///    <para> 
        ///       Initializes a new instance of <see cref='System.Web.UI.Design.DataColumnSelectionConverter'/>.
        ///    </para> 
        /// </devdoc> 
        public DataColumnSelectionConverter() {
        } 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.CanConvertFrom"]/*' />
        /// <devdoc>
        ///    <para> 
        ///       Gets a value indicating whether this converter can
        ///       convert an object in the given source type to the native type of the converter 
        ///       using the context. 
        ///    </para>
        /// </devdoc> 
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) {
            if (sourceType == typeof(string)) {
                return true;
            } 
            return false;
        } 
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.ConvertFrom"]/*' />
        /// <devdoc> 
        ///    <para>
        ///       Converts the given object to the converter's native type.
        ///    </para>
        /// </devdoc> 
        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) {
            if (value == null) { 
                return String.Empty; 
            }
            else if (value.GetType() == typeof(string)) { 
                return (string)value;
            }
            throw GetConvertFromException(value);
        } 

        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValues"]/*' /> 
        /// <devdoc> 
        ///    <para>
        ///       Gets the data fields of the bound fields and autogenerated fields in the current gridview for the 
        ////      RowHeaderColumn and SummaryHeaderColumn properties.
        ///    </para>
        /// </devdoc>
        public override StandardValuesCollection GetStandardValues(ITypeDescriptorContext context) { 
            string[] names = null;
            ArrayList namesList = new ArrayList(); 
 
            if (context != null) {
                IComponent component = context.Instance as IComponent; 
                if (component != null) {
                    GridView gridView = component as GridView;
                    if (gridView != null) {
                        if (gridView.AutoGenerateColumns) { 
                            // add all the fields
                            DataFieldConverter dataFieldConverter = new DataFieldConverter(); 
                            StandardValuesCollection values = dataFieldConverter.GetStandardValues(context); 
                            foreach (object value in values) {
                                namesList.Add(value); 
                            }
                        }
                        DataControlFieldCollection fields = gridView.Columns;
                        foreach (DataControlField field in fields) { 
                            BoundField boundField = field as BoundField;
                            if (boundField != null) { 
                                string dataField = boundField.DataField; 
                                if (!namesList.Contains(dataField)) {
                                    namesList.Add(dataField); 
                                }
                            }
                        }
 
                        namesList.Sort();
                        names = new string[namesList.Count]; 
                        namesList.CopyTo(names, 0); 
                    }
                } 
            }
            return new StandardValuesCollection(names);
        }
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValuesExclusive"]/*' />
        /// <devdoc> 
        ///    <para> 
        ///       Gets a value indicating whether the collection of standard values returned from
        ///    <see cref='System.ComponentModel.TypeConverter.GetStandardValues'/> is an exclusive 
        ///       list of possible values, using the specified context.
        ///    </para>
        /// </devdoc>
        public override bool GetStandardValuesExclusive(ITypeDescriptorContext context) { 
            return false;
        } 
 
        /// <include file='doc\DataColumnSelectionConverter.uex' path='docs/doc[@for="DataColumnSelectionConverter.GetStandardValuesSupported"]/*' />
        /// <devdoc> 
        ///    <para>
        ///       Gets a value indicating whether this object supports a standard set of values
        ///       that can be picked from a list.
        ///    </para> 
        /// </devdoc>
        public override bool GetStandardValuesSupported(ITypeDescriptorContext context) { 
            if (context != null && context.Instance is IComponent) { 
                // We only support the dropdown in single-select mode.
                return true; 
            }
            return false;
        }
    } 
}

// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
