//------------------------------------------------------------------------------ 
// <copyright file="DataSetFieldSchema.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

namespace System.Web.UI.Design { 
 
    using System.Data;
 
    /// <devdoc>
    ///    <para>
    ///       Provides schema information for a single field.  This schema information is used at
    ///       at designtime to make decisions about what fields should be shown in field 
    ///       pickers for DataKeyField for DataBound controls, etc.
    ///    </para> 
    /// </devdoc> 
    public sealed class DataSetFieldSchema : IDataSourceFieldSchema {
 
        private DataColumn _column;

        public DataSetFieldSchema (DataColumn column) {
            if (column == null) { 
                throw new ArgumentNullException("column");
            } 
            _column = column; 
        }
 
        /// <devdoc>
        /// Returns a type object representing the type of data in the field.
        /// </devdoc>
        public Type DataType { 
            get {
                return _column.DataType; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the value of the field is generated by the database.
        /// </devdoc>
        public bool Identity { 
            get {
                return _column.AutoIncrement; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the field value cannot be changed.
        /// </devdoc>
        public bool IsReadOnly { 
            get {
                return _column.ReadOnly; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if a constraint of this field is that its value must be unique.
        /// </devdoc>
        public bool IsUnique { 
            get {
                return _column.Unique; 
            } 
        }
 
        /// <devdoc>
        /// Returns the max length of the field, or -1 if none is specified.
        /// </devdoc>
        public int Length { 
            get {
                return _column.MaxLength; 
            } 
        }
 
        /// <devdoc>
        /// Returns the name of the field.
        /// </devdoc>
        public string Name { 
            get {
                return _column.ColumnName; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the field can take null values.
        /// </devdoc>
        public bool Nullable { 
            get {
                return _column.AllowDBNull; 
            } 
        }
 
        public int Precision {
            get {
                return -1;
            } 
        }
 
        /// <devdoc> 
        /// Returns true if this field is a key field of its view.
        /// </devdoc> 
        public bool PrimaryKey {
            get {
                if ((_column.Table == null) || (_column.Table.PrimaryKey == null)) {
                    return false; 
                }
                foreach (DataColumn c in _column.Table.PrimaryKey) { 
                    if (c == _column) { 
                        return true;
                    } 
                }
                return false;
            }
        } 

        public int Scale { 
            get { 
                return -1;
            } 
        }
    }
}
 

// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
//------------------------------------------------------------------------------ 
// <copyright file="DataSetFieldSchema.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

namespace System.Web.UI.Design { 
 
    using System.Data;
 
    /// <devdoc>
    ///    <para>
    ///       Provides schema information for a single field.  This schema information is used at
    ///       at designtime to make decisions about what fields should be shown in field 
    ///       pickers for DataKeyField for DataBound controls, etc.
    ///    </para> 
    /// </devdoc> 
    public sealed class DataSetFieldSchema : IDataSourceFieldSchema {
 
        private DataColumn _column;

        public DataSetFieldSchema (DataColumn column) {
            if (column == null) { 
                throw new ArgumentNullException("column");
            } 
            _column = column; 
        }
 
        /// <devdoc>
        /// Returns a type object representing the type of data in the field.
        /// </devdoc>
        public Type DataType { 
            get {
                return _column.DataType; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the value of the field is generated by the database.
        /// </devdoc>
        public bool Identity { 
            get {
                return _column.AutoIncrement; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the field value cannot be changed.
        /// </devdoc>
        public bool IsReadOnly { 
            get {
                return _column.ReadOnly; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if a constraint of this field is that its value must be unique.
        /// </devdoc>
        public bool IsUnique { 
            get {
                return _column.Unique; 
            } 
        }
 
        /// <devdoc>
        /// Returns the max length of the field, or -1 if none is specified.
        /// </devdoc>
        public int Length { 
            get {
                return _column.MaxLength; 
            } 
        }
 
        /// <devdoc>
        /// Returns the name of the field.
        /// </devdoc>
        public string Name { 
            get {
                return _column.ColumnName; 
            } 
        }
 
        /// <devdoc>
        /// Returns true if the field can take null values.
        /// </devdoc>
        public bool Nullable { 
            get {
                return _column.AllowDBNull; 
            } 
        }
 
        public int Precision {
            get {
                return -1;
            } 
        }
 
        /// <devdoc> 
        /// Returns true if this field is a key field of its view.
        /// </devdoc> 
        public bool PrimaryKey {
            get {
                if ((_column.Table == null) || (_column.Table.PrimaryKey == null)) {
                    return false; 
                }
                foreach (DataColumn c in _column.Table.PrimaryKey) { 
                    if (c == _column) { 
                        return true;
                    } 
                }
                return false;
            }
        } 

        public int Scale { 
            get { 
                return -1;
            } 
        }
    }
}
 

// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
