//------------------------------------------------------------------------------ 
// <copyright file="ToolStripDropDownItemDesigner.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

/* 
 */ 

 [assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="System.Windows.Forms.Design.ToolStripDropDownItemDesigner..ctor()")] 
namespace System.Windows.Forms.Design {

    using System;
    using System.Collections; 
    using System.ComponentModel;
    using System.ComponentModel.Design; 
    using System.Design; 
    using System.Windows.Forms;
    using System.Drawing; 

    /// <summary>
    /// Designer for ToolStripDropDownItems.  This is here so only the
    /// dropdown items get the "Edit Items..." verb. 
    /// </summary>
    internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner 
    { 
        /// <summary>
        ///  Initialize the item. 
        /// </summary>
        public override void Initialize(IComponent component)
        {
            base.Initialize (component); 

        } 
 
        /// <summary>
        ///  The ToolStripItems are the associated components. 
        ///  We want those to come with in any cut, copy opreations.
        /// </summary>
        public override System.Collections.ICollection AssociatedComponents {
           get { 
                ToolStripDropDownItem item = Component as ToolStripDropDownItem;
                if (item != null && item.DropDown.IsAutoGenerated) { 
                    return item.DropDownItems; 
                }
                return base.AssociatedComponents; 
           }
        }
    }
} 


// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
//------------------------------------------------------------------------------ 
// <copyright file="ToolStripDropDownItemDesigner.cs" company="Microsoft">
//     Copyright (c) Microsoft Corporation.  All rights reserved.
// </copyright>
//----------------------------------------------------------------------------- 

/* 
 */ 

 [assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope="member", Target="System.Windows.Forms.Design.ToolStripDropDownItemDesigner..ctor()")] 
namespace System.Windows.Forms.Design {

    using System;
    using System.Collections; 
    using System.ComponentModel;
    using System.ComponentModel.Design; 
    using System.Design; 
    using System.Windows.Forms;
    using System.Drawing; 

    /// <summary>
    /// Designer for ToolStripDropDownItems.  This is here so only the
    /// dropdown items get the "Edit Items..." verb. 
    /// </summary>
    internal class ToolStripDropDownItemDesigner : ToolStripItemDesigner 
    { 
        /// <summary>
        ///  Initialize the item. 
        /// </summary>
        public override void Initialize(IComponent component)
        {
            base.Initialize (component); 

        } 
 
        /// <summary>
        ///  The ToolStripItems are the associated components. 
        ///  We want those to come with in any cut, copy opreations.
        /// </summary>
        public override System.Collections.ICollection AssociatedComponents {
           get { 
                ToolStripDropDownItem item = Component as ToolStripDropDownItem;
                if (item != null && item.DropDown.IsAutoGenerated) { 
                    return item.DropDownItems; 
                }
                return base.AssociatedComponents; 
           }
        }
    }
} 


// File provided for Reference Use Only by Microsoft Corporation (c) 2007.
// Copyright (c) Microsoft Corporation. All rights reserved.
